# Basic
title: Anttu
author: Anttu
subtitle: 个人站
description: 欢迎来到我的个人站~
# 头像里面的标题
avatarTitle: Anttu
# 头像里面的描述
avatarDesc: Java | linux
url: "https://anttutu.github.io"

# Comment
comment:
    # disqus: 
    # duoshuo: 
      youyan: 2135147

# gitment
# gitment: anTtutu
          # id: 581bd96523e3f5c2eff6
          # secret: 6ae18be198d13f2a5d023c71effddddfd48b107a

# Social
social:
    weibo: 5574617638
    github: anTtutu
    csdn: anttu
    # twitter: 
    mail: anttu0531@gmail.com
    # gplus: anttu0531

# 百度统计 
# 使用博客模板请去掉或者更换 id 
baidu:
    id: f840ee1cf94942747467436f33412e09  

# Google Analytics
# 使用博客模板请去掉或者更换 id
ga:
   id: UA-101226804-1    
   host: auto  

# Github
github:
   user: anTtutu
   repo: anTtutu.github.io

# 《----------------- 上面的信息修改成你自己的 ---------------------------》
#
#
#  _post/ 下的文章更换成你自己的文章
#  帮忙star一下，感谢~😆 地址： https://github.com/anTtutu/anTtutu.github.io
#
#
# 《--------------- 下面的信息可以自行选择是否修改 ------------------------》


permalink: /:year/:month/:title/

markdown: kramdown

kramdown:
  input:  GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: true
  extensions:
    - autolink
    - footnotes
    - smart
  syntax_highlighter: rouge

# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 博客主页

# Navigation buttons in the front page.s
nav:
    - {title: 归档, description: archive, url: '/archive'}   
    - {title: 分类, description: tags, url: '/tags'}
    - {title: 留言, description: messages, url: '/messages'}      
    - {title: 关于, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 10
paginate_path: "page/:num/"
